// =============================================================
// farm.dart
// Model: Farm (Trang trại)
// Ánh xạ từ bảng iot_Farms
// =============================================================

class Farm {
  final int? farmId;  // Nullable when creating new farms (auto-generated by DB)
  final String farmerId;  // Stored as string userId from FarmerProfiles
  final String farmName;
  final String location;
  final double areaHectares;
  final String cropType;
  final int isVerified;  // 0 or 1
  final String? certifications;

  Farm({
    this.farmId,
    required this.farmerId,
    required this.farmName,
    required this.location,
    required this.areaHectares,
    required this.cropType,
    this.isVerified = 0,
    this.certifications,
  });

  /// Convert Map từ database thành Farm object
  factory Farm.fromMap(Map<String, dynamic> map) {
    return Farm(
      farmId: map['FarmId'] as int?,
      farmerId: (map['FarmerId'] ?? '').toString(),  // Convert to string for consistency
      farmName: map['FarmName'] ?? '',
      location: map['Location'] ?? '',
      areaHectares: (map['AreaHectares'] as num?)?.toDouble() ?? 0.0,
      cropType: map['CropType'] ?? '',
      isVerified: (map['IsVerified'] as int?) ?? 0,
      certifications: map['Certifications'],
    );
  }

  /// Convert Farm object thành Map cho database
  Map<String, dynamic> toMap() {
    final map = {
      'FarmerId': int.tryParse(farmerId) ?? 0,  // Convert string userId to integer for DB
      'FarmName': farmName,
      'Location': location,
      'AreaHectares': areaHectares,
      'CropType': cropType,
      'IsVerified': isVerified,
      'Certifications': certifications,
    };
    // Only include FarmId if it's not null (for updates)
    if (farmId != null) {
      map['FarmId'] = farmId;
    }
    return map;
  }

  /// Tạo bản sao với một số trường được thay thế
  Farm copyWith({
    int? farmId,
    String? farmerId,
    String? farmName,
    String? location,
    double? areaHectares,
    String? cropType,
    int? isVerified,
    String? certifications,
  }) {
    return Farm(
      farmId: farmId ?? this.farmId,
      farmerId: farmerId ?? this.farmerId,
      farmName: farmName ?? this.farmName,
      location: location ?? this.location,
      areaHectares: areaHectares ?? this.areaHectares,
      cropType: cropType ?? this.cropType,
      isVerified: isVerified ?? this.isVerified,
      certifications: certifications ?? this.certifications,
    );
  }

  @override
  String toString() =>
      'Farm(farmId: $farmId, farmName: $farmName, cropType: $cropType)';
}
